### ISSUE TITLE
Differences to inetbox2mqtt?

### ISSUE THREAD

**Issue by 7wells** [Fabian-Schmidt/esphome-truma_inetbox#1]
Hi Fabian!

I'm using Magnus' inetbox2mqtt on an ESP32 with UART-LIN adapter and CP+ and can thus control my Truma Combi 4. Now I kind of stumbled over your project (Magnus starred it here on GitHub), and I am not yet quite sure if I understand the differences between your project and Magnus' inetbox2mqtt. Please forgive me my fault, if I might have overseen something. It would be great if you added a few lines of explanation (if your time permits it, of course). Thank you so much, and my best regards to you!😃

**Comment by Fabian-Schmidt** [comment]
Hi,
Yes you can add more sensors. I currently building a status display.
Just one ESP32 with Display, RTC, a bunch of Bluetooth sensors and the Truma Lin interface. And this is more or less now just configuration using ESP Home.

![Pic](https://user-images.githubusercontent.com/4003089/221382157-9acf64fa-2247-4c72-b90c-fbf7af3b8138.jpg)

Top is information from my Victron Smart Shunt (via BT), Victron Smart Solar (via BT), current temperature of the Truma and last Gas tank sensor (via BT). All without HA just the ESP alone.

My ESP32 has 320kb of RAM. I do have issues when using Bluetooth, Display and Wifi.

**Comment by snipah** [comment]
Hi Fabian! Just switched from inetbox2mqtt to your implementation because I prefer the hassle free config/update-procedure via Wireguard from everywhere! Thanks! 
I have https://github.com/KinDR007/VictronMPPT-ESPHOME running on a separate 8266 for a Shunt and Smart Solar. Can I ass the victrun-stuff to the same ESP your Truma-implementation is running on?

**Comment by Fabian-Schmidt** [comment]
No this is using a Mopeka (Standard) Gas Sensor. They are already supported by ESP Home.

**Comment by snipah** [comment]
> No this is using a Mopeka (Standard) Gas Sensor. They are already supported by ESP Home.

This is great news! Ordered the mopeka standard yesterday and switched to esphome-dev already.
