### ISSUE TITLE
Installing yaml shows error about logger not configured

### ISSUE THREAD

**Issue by 7wells** [Fabian-Schmidt/esphome-truma_inetbox#11]
Hi Fabian,

The installation of the (slightly modified) truma.yaml seems to run fine, as it ends with:
> INFO Successfully uploaded program.

However, the last line (below) reads:
> ERROR Logger is not configured!

Is it simply, because my ESP32 is still sitting on my desk (i.e. not connected yet to the Truma) and/or because I need to do something else? Precisely, what logger do I have to configure and where?

Thank you very much! :)

**Comment by Fabian-Schmidt** [comment]
When you are building your yaml without a  [logger component](https://esphome.io/components/logger.html) then this message is expected.
