### ISSUE TITLE
DS1307 RTC?

### ISSUE THREAD

**Issue by 7wells** [Fabian-Schmidt/esphome-truma_inetbox#14]
Hi Fabian and other users!

Do you use a DS1307 RTC attached to a Raspberry Pi and could share some details about wiring and setting it up? Thanks for your time and help!

**Comment by Fabian-Schmidt** [comment]
The Crystal warning has no relationship to the DS107 RTC or anything of ESP Home (and this component).
The Crystal oscillator is an Electromechanical component on the ESP32 board. It might be impacted by temperature and movement etc. Typically not this strong. It might be a cheap quality.
If you have issues with Wifi or Bluetooth connection / reception this might  cause it. As the crystal is used to generate the Wifi/Bt frequencies.
