### ISSUE TITLE
Without DS1307/ time?

### ISSUE THREAD

**Issue by 7wells** [Fabian-Schmidt/esphome-truma_inetbox#15]
Hi Fabian!

Do I understand it right that your tool also works without DS1307/ time?
https://github.com/Fabian-Schmidt/esphome-truma_inetbox/commit/29386094cbdb6d1f9c34b81b30dbf433c75a5844

Would I have to change the yaml config or should I leave the time-related stuff untouched?

I ask because I burnt my DS1307. 😳

**Comment by Fabian-Schmidt** [comment]
Yes it works without time.

You can remove them from the yaml or leave them in. If you leave them in you will get a warning on boot that it cannot find the DS1307.
