### ISSUE TITLE
Operating Status 1 to 5

### ISSUE THREAD

**Issue by snipah** [Fabian-Schmidt/esphome-truma_inetbox#23]
Do we have any idea, what Operating Status 1 to 5 means? 5 is obviously "Heating Mode".

**Comment by snipah** [comment]
Not needed anymore

**Comment by 7wells** [comment]
@snipah 
Have you found out what the numbers mean?

**Comment by snipah** [comment]
> @snipah Have you found out what the numbers mean?

This is what I found out and what I'm using... 

`
- platform: template
    sensors:
      truma_status:
        friendly_name: "Truma Operating Status"
        value_template: >-
          {% set status_mapping = {
            0: "Aus",
            1: "Warnung",
            4: "Start/ Cool Down",
            5: "Heizen (5)",
            6: "Heizen (6)",
            7: "Heizen (7)"
          } %}
          {{ status_mapping[states('sensor.esp_poessl_operating_status')|int] if states('sensor.esp_poessl_operating_status')|int in status_mapping else 'Ungültig' }}`

**Comment by 7wells** [comment]
Thanks! Do you know why "Heizen" has 3 different codes?

BTW:
https://poesslforum.de/forum/elektrik/32494-smartavan-fernsteuerung-truma-heizung?start=100#509968

😉

**Comment by 7xy** [comment]
>   0: "Aus",
>   1: "Warnung",
>   4: "Start/ Cool Down",
>   5: "Heizen (5)", Status bei der Combi E wenn die Heizung an ist und kein Landstrom anliegt
>   6: "Heizen (6)", Status der Combi E, wenn die Heizung am CP Plus ausgeschaltet wurde und Landstrom anliegt
>   7: "Heizen (7)" Status bei der Combi E wenn die Heizung an ist und Landstrom anliegt

War zumindest meine Feststellung an meiner Combi 6E
![Image](https://github.com/user-attachments/assets/39cc5362-179c-4df7-8d9e-2e07a93c5845)
