### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by 7wells** [Fabian-Schmidt/esphome-truma_inetbox#3]
Hi Fabian, please forgive me my maybe stupid question, but do you have some recommendation how to install your code? I'm familiar (a bit) with the ESP32, uPython, and was able to get inetbox2mqtt running on my other ESP32 but have no idea how to start with your project. Thanks for your hints (and patience)! ☺️

**Comment by Fabian-Schmidt** [comment]
Hi,
If you have already a Home Assistant running there is this guide for getting started with ESPHome
https://esphome.io/guides/getting_started_hassio.html

If you don't have Home assistant it gets a bit more complex and there is another guide for it:
https://esphome.io/guides/getting_started_command_line.html

I see ESP Home as a lot of building blocks to build your ESP project. Just start with a very simple one from the example and then add this component to it.

**Comment by Fabian-Schmidt** [comment]
That's the great thing of ESP Home that you don't have to worry about these things too much. Once the device is setup for ESP Home you can give your HA your yaml configuration file. HA (Pi4) will detect the components and build the firmware for your device and then upload it to the ESP.

**Comment by snipah** [comment]
Simply copy the [truma.yml](https://github.com/Fabian-Schmidt/esphome-truma_inetbox/blob/main/truma.yaml) and - after clicking edit - replace the prefilled code by pasting the truma.yml. Then edit it according to your needs (e. g. enter your Wifi-Credentials and paste , save and press install, which then will try to compile the code and install it on the ESP via your USB-connection. If everything was done properly (ESP is shown as 'online' in ESPhome) , it can even be installed wirelessly.

**Comment by Fabian-Schmidt** [comment]
This is just an example config. I don't actually use them anywhere.
