### ISSUE TITLE
unknown tag !<!lambda> (145:11) in /config/esphome/esp32.yaml

### ISSUE THREAD

**Issue by 7wells** [Fabian-Schmidt/esphome-truma_inetbox#9]
@Fabian-Schmidt @snipah
After installing the (slightly modified) truma.yaml on my ESP32, I see a warning in the HA File editor for the `/config/esphome/esp32.yaml` file:

> unknown tag !<!lambda> (145:11)
> 
> ```
>  142 |           # You can use lambda functions
>  143 |           temperature: !lambda |-
>  144 |             return 16;
>  145 |           # Optional set heating mode: `" ...
> -----------------^
>  146 |           heating_mode: ECO
>  147 |     turn_off_action:
> ```

What is it about the unknown tag? Thanks for your help!

**Comment by Fabian-Schmidt** [comment]
After changing the yaml config file a new build for the ESP must be triggered and a new version must be uploaded to the ESP device.
This can be done via wifi. if WiFi and OTA (over the air) updates are configured.

I cannot comment on the warning in the HA file editor as I don't use HA.
